apiVersion: apps/v2
kind: Deployment
metadata:
  name: passengersurvivedv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mldeployment
  template:
    metadata:
      labels:
        app: mldeployment
    spec:
      containers:
      - name: ml-app
        image: gcr.io/neat-throne-343419/myapp:v2
        ports:
        - containerPort: 8080